In [20]:
import pandas as pd
import io
df = pd.read_csv('DDW_B18sc_3300_NIC_FINAL_STATE_TAMIL_NADU-2011.csv')

final = pd.DataFrame(df.TotalPersons)
print(final)

print("\nMeasure of total workers\n***************************")
print("Mean : ",final.mean())
print("Median : ",final.median())
print("Mode : ",final.mode())

    TotalPersons
0        2568994
1         139687
2            770
3             88
4             12
5            314
6            173
7             35
8            148
9          64149
10             6
11            68
12             3
13           139
14          4491
15         58431
16           358
17           653
18           118

Measure of total workers
***************************
Mean :  TotalPersons    149401.947368
dtype: float64
Median :  TotalPersons    173.0
dtype: float64
Mode :      TotalPersons
0              3
1              6
2             12
3             35
4             68
5             88
6            118
7            139
8            148
9            173
10           314
11           358
12           653
13           770
14          4491
15         58431
16         64149
17        139687
18       2568994